spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Pass2020!
  data:
    r2dbc:
      repositories:
        enabled: true
logging:
  level:
    org.springframework.data.r2dbc: Debug